### ISSUE TITLE
Tail call optimization not working

### ISSUE THREAD

**Issue by Axnyff** [codetower/es6-features#2]
The evaluate button doesn't work for the tail call optimization example, it writes 

SyntaxError: Unexpected number .

This seems to be linked to how the code is converted to be runned. 

It is indeed converted to

`function factorial(n, acc = 1) {

    if (n 1) return acc;
    return factorial(n - 1, n * acc);
}`
according to the console.

I tried changing &lt; to <= but it doesn't seems to fix anything.

I'd be happy to provide any help if needed.

**Comment by saspre** [comment]
Yeah. It fails because in an attempt to remove the highlight attributes in the source it catches the `<=` part. 

I made a quick fix by reversing the order in the markdown. This is the quick solution. 
I will make a more general solution later such that `<` can be used.

**Comment by Axnyff** [comment]
I made a pull request to slightly change the regex. Anyway, your actual solution is working for the moment. Thanks!

**Comment by saspre** [comment]
I made a proper solution now. By removing tags before we convert `&lt;` to `<` we avoid the problem entirely. I also refactored the code so it is now more appealing (if you are into OOP).
